update test script, dependencies
old test:
```
λ npm test

> remarkable-meta@1.0.1 test C:\Users\tom-byrer\Documents\dev\learn\js\remarkable\remarkable-meta
> tape test/*.js

module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\Users\tom-byrer\Documents\dev\learn\js\remarkable\remarkable-meta\test\*.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at C:\Users\tom-byrer\Documents\dev\learn\js\remarkable\remarkable-meta\node_modules\tape\bin\tape:5:5
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\tom-byrer\Documents\dev\learn\js\remarkable\remarkable-meta\node_modules\tape\bin\tape:4:23)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
npm ERR! Test failed.  See above for more details.
```

Also updated versions, tag.